### ISSUE TITLE
I have 2 questions,but i don't if i should write them here

### ISSUE THREAD

**Issue by qooweds** [aillieo/LoadRunner-protobuf-demo#1]
感谢!找到您的博客了,我先拜读一下

**Comment by aillieo** [comment]
1. 主要有三个文件夹
**lr_pb** 是LoadRunner的虚拟用户脚本文件夹 里边的文件都在LR创建的
**pb_dll** 是VS的DLL工程文件
**pb_msg** 是protobuf生成消息用到的文件

2. LoadRunner官方有使用winsocket的[api手册](http://lrhelp.saas.hpe.com/en/12.53/help/function_reference/FuncRef.htm#winsocket/etc/lrFuncRef_WSOC_Alphbtcl_Lst_Funcs.htm)
专门使用protobuf的文档暂时没有找到

**Comment by qooweds** [comment]
多谢!
issue我还不是很会用,把之前的回复删掉了,抱歉

**Comment by aillieo** [comment]
没关系 欢迎切磋交流
